### ISSUE TITLE
BioC2020 workshop requirements

### ISSUE THREAD

**Issue by lwaldron** [LieberInstitute/recountWorkshop2020#1]
Are you still planning to present this at BioC2020? If so, please follow the template provided at https://bioc2020.bioconductor.org and make sure it passes checks by July 16, otherwise it will have to be removed from the program.

**Comment by mdozmorov** [comment]
@lcolladotor, is this package going to be presented? Today, July 16, is the last day for modifications.

**Comment by lcolladotor** [comment]
Hi,

I still plan to present this workshop. I was away for vacations July 10 to 19th on a camping trip with no internet so I missed these messages. I'll work on it later today.

Best,
Leo

**Comment by mdozmorov** [comment]
Thanks, Leo, no problem, that's what summer is for. Your workshop is scheduled for Monday, 7/27, 3:00pm ET, I hope it'll be up soon.

**Comment by mdozmorov** [comment]
@lcolladotor, checking about the status of the workshop. It needs to conform to the template https://github.com/seandavi/BuildABiocWorkshop2020.

**Comment by mdozmorov** [comment]
The Pkgdown web site is missing. Seems like you need to add _pkgdown.yml, like https://github.com/seandavi/BuildABiocWorkshop2020/blob/master/_pkgdown.yml, and let GH actions to do the job.

**Comment by lcolladotor** [comment]
Hi @mdozmorov,

The `pkgdown` site is there. It's generated by https://github.com/LieberInstitute/recountWorkshop2020/blob/master/.github/workflows/check-bioc.yml#L270-L290 under the `gh-pages` branch at https://github.com/LieberInstitute/recountWorkshop2020/tree/gh-pages and deployed at https://LieberInstitute.github.io/recountWorkshop2020. The GitHub Actions (GHA) workflow I'm using is the one from [`biocthis`](https://lcolladotor.github.io/biocthis/index.html) and the GHA lines related to `pkgdown` are from `r-lib/actions`. It's different from Sean Davis' code that deploys the `pkgdown` files to `gh-pages` using other code instead of `pkgdown::deploy_to_branch()`.

I just added to the `biocthis` GHA the lines of code related to docker from Sean at https://github.com/seandavi/BuildABiocWorkshop2020. As an extra, the `biocthis` GHA also tests on Windows and macOS, in addition to the Bioconductor devel docker environment (linux).


Anyway, today I adapted the 2hr 2019 workshop to fit the 50-55 min window for 2020.

Best,
Leo

**Comment by mdozmorov** [comment]
Thanks, Leo. If you change the URL in your DESCRIPTION file to https://LieberInstitute.github.io/recountWorkshop2020/, then the web site will be correct on the BioC2020 web site. You can see all workshops are linked to Pkgdown sites, except yours  https://bioc2020.bioconductor.org/workshops

**Comment by lcolladotor** [comment]
Ok! I just pushed the changes

**Comment by mdozmorov** [comment]
Looks great. Good luck with your workshop!

**Comment by lcolladotor** [comment]
Thanks =)
